### ISSUE TITLE
Suggested Mod Additions

### ISSUE THREAD

**Issue by ZoeZoePixel** [RyanP1991/TWPI-Custom-Pack---1.12#1]
Dynamic Surroundings [https://minecraft.curseforge.com/projects/dynamic-surroundings](url)
Mo' Villages [https://minecraft.curseforge.com/projects/mo-villages](url)
would LOVE it if you add serene sessons & plus tic

**Comment by ZoeZoePixel** [comment]
another nice client side mod would be 
DiscordSuite [https://minecraft.curseforge.com/projects/discordsuite](url)

**Comment by RyanP1991** [comment]
Dynamic Surroundings added, other two rejected.
