### ISSUE TITLE
Infinitely High Sugarcane

### ISSUE THREAD

**Issue by Hekera** [RyanP1991/TWPI-Custom-Pack---1.12#102]
I thought this was a feature, not a bug, but since everyone is peeved by it here's the fix:
Go to the Apotheosis config folder, and open the file named "garden"
The following lines will appear, which you may change to suit whatever the max growth height should be:
`# The max height a stack of cacti may grow to. [range: 1 ~ 255, default: 5]
    I:"Cactus Height"=5`

` # The max height a stack of reeds may grow to. [range: 1 ~ 255, default: 255]
    I:"Reed Height"=255`

**Comment by RyanP1991** [comment]
Changed to 5
