### ISSUE TITLE
EZStrorage 2 Mod Suggestion 

### ISSUE THREAD

**Issue by nefolaC4** [RyanP1991/TWPI-Custom-Pack---1.12#103]
EZStorage 2 is a simplified and lower power level AE style mod. In addition to wanting to play with this mod, I also think it's use might reduce lag.

Here is a link to the [mod](https://www.curseforge.com/minecraft/mc-mods/ezstorage-2).

**Comment by RyanP1991** [comment]
Not neeeded this time, thank you for the suggestion though
