### ISSUE TITLE
Nether mob spawnrate adjustments

### ISSUE THREAD

**Issue by Hekera** [RyanP1991/TWPI-Custom-Pack---1.12#104]
1. Reduce spawnrate of hellhounds or remove them entirely in the Quark config. They spawn much too often and can even hinder the spawnrates of other nether mobs.
2. Increase spawnrate of wither skeletons and ghasts, which almost never appear.

**Comment by RyanP1991** [comment]
I will remove the hellhounds this should help with part 2

**Comment by RyanP1991** [comment]
Decreased hellhound chance drastically
