### ISSUE TITLE
Increase Advanced Rocketry O2 vent radius

### ISSUE THREAD

**Issue by Hekera** [RyanP1991/TWPI-Custom-Pack---1.12#106]
Can the radius be increased to 64 or something? The config currently has:
`# Radius of the O2 vent.  if atmosphereCalculationMethod is 2 or 3 then max volume is calculated from this radius.  WARNING: larger numbers can lead to lag
    I:oxygenVentSize=32`

**Comment by RyanP1991** [comment]
Done to 64 let me know if you want to try a higher number
