### ISSUE TITLE
Ultimate Stew Recipe borked

### ISSUE THREAD

**Issue by Hekera** [RyanP1991/TWPI-Custom-Pack---1.12#115]
You probably already know this, this is just a reminder. The ultimate stew recipe is completely different from previous versions.

**Comment by RyanP1991** [comment]
Does this recipe work at all?

**Comment by Hekera** [comment]
The new recipe does work, so technically no need to change it but iirc Ricc was kinda upset that he bred a whole bunch of trees and grew a lot of plants only to find that some of them changed. Personally idrc what happens, you can leave it and maybe see how its affected Ricardo and ameliorate the issue for just him, or change it back to how it was

**Comment by RyanP1991** [comment]
I left it alone in the update
