### ISSUE TITLE
Make Excavate enchant book craftable

### ISSUE THREAD

**Issue by Hekera** [RyanP1991/TWPI-Custom-Pack---1.12#118]
Add a couple recipes to the EnderIO enchanter (or other enchanted book creating device of your choice) that take excavate modifiers to create an Excavate (I-V) book. The only reason I am requesting this is because it seems that the enchant  is either exceedingly rare or impossible to obtain via the normal enchant table.

**Comment by RyanP1991** [comment]
Done
