### ISSUE TITLE
Recipe Conflict and Missing Upgrades

### ISSUE THREAD

**Issue by Earthgamez** [RyanP1991/TWPI-Custom-Pack---1.12#13]
The recipe for the RFTools Empty Dimension Tab and the Miniature Recipe from LittleTiles have a recipe conflict

Also, I noticed ever since Mob Grinding Utils was updated in the last pack update, upgrades in the mob mashers would disappear after each server restart and the masher would stop working with a redstone signal.

**Comment by RyanP1991** [comment]
Sorted in 1.0.8
