### ISSUE TITLE
Thaumcraft Crash

### ISSUE THREAD

**Issue by acanady** [RyanP1991/TWPI-Custom-Pack---1.12#2]
I keep getting a crash with Thaumcraft, something having to do with a pech?
Here's the link to the crashlog thanks to VanillaFix. Man, love that mod.

https://paste.dimdev.org/acunosuvug.mccrash

**Comment by acanady** [comment]
It's  happened twice already

**Comment by RyanP1991** [comment]
You will need to remove Hats for now, it is a known issue. Hats will be removed in the next update until they work together with Thaumcraft and Hats

"https://github.com/Azanor/thaumcraft-beta/issues/616"

**Comment by acanady** [comment]
thx

**Comment by RyanP1991** [comment]
Pack update has fixed this in which hats will only appear on non modded mobs, so Hats has returned.
