### ISSUE TITLE
No recipe for enchanted golden apple

### ISSUE THREAD

**Issue by Hachuurui** [RyanP1991/TWPI-Custom-Pack---1.12#20]
Normally is an apple with 8 gold blocks around it.

I recommend changing this to be 8 gold blocks and a supremium apple (red one) in a Extra Utils Enchanter.

I would say about 64k rf cost would be fine so maybe make the cost match evil ingot but only give one apple.

**Comment by Hachuurui** [comment]
Although if you think I'm being to evil on that recipe, you could always do the other one. Up to you.

**Comment by RyanP1991** [comment]
Done for 1.0.10
