### ISSUE TITLE
Add Recipes for new Refined Storage Processors to work in other Furnaces/Smelters.

### ISSUE THREAD

**Issue by Hachuurui** [RyanP1991/TWPI-Custom-Pack---1.12#31]
Currently, You can only make them in Furnace, Redstone Furnace, Extra Utilities Furnace, and Ender IO Alloy Smelter. 

We need recipes for other smelters/furnaces.

**Comment by Hachuurui** [comment]
Mekanism: Energized Smelter, Basic Smelting Factory, Advanced Smelting Factory, Elite Smelting Factory
Actual Additions: Powered Furnace
Mystical Agriculture: Inferium, Prudentium, Intermedium, Superium, Supremium, Ultimate Furnaces

**Comment by Hachuurui** [comment]
Closing as they are recognized but not listed in JEI

**Comment by RyanP1991** [comment]
Will add a JEI tooltip to explain this in 1.0.12
