### ISSUE TITLE
Multiple Resource Mods

### ISSUE THREAD

**Issue by Starr12** [RyanP1991/TWPI-Custom-Pack---1.12#37]
Discuss: Should we keep all 4?

Bees
Chickens
Environmental Tech
Mystical Agriculture

**Comment by RyanP1991** [comment]
So if we go through all of them we have:

- Advanced Rocketry
- Agricraft
- Blood Magic
- Bees
- Chickens
- Enviromental Tech
- Immersive Engineering
- Industrial Foregoing
- RF Tools
- Deep Mob Learning
- Mystical Agriculuture

**Comment by Starr12** [comment]
Okay, but most of those mods do other stuff, like Access to machines, those 4 mods are basically dedicated to creating infinite resources. IE has very visual machines and decorations and doesn't REALLY have a source of infinite ores(even if those ores counts are so massive they become "so much ill never need more), IF has Unique machines for mob grinding and unique materials. blood magic has usable spells for combat,.... ETC

**Comment by Jadziyah** [comment]
Bees are not just dedicated to creating infinite resources. They are also necessary for tree/flower breeding in Forestry and Binnie's Mods.

**Comment by RyanP1991** [comment]
Bees are staying no matter what.
