### ISSUE TITLE
Spawn Temple placed me in a wall in a new world

### ISSUE THREAD

**Issue by Starr12** [RyanP1991/TWPI-Custom-Pack---1.12#38]
Seed: -3061687515083613664
World type Default

If this pack is mostly for the server, should we even keep this mod when the server will only generate the one castle anyway?

**Comment by RyanP1991** [comment]
True I just thought this would just build a safe area at spawn I can simply remove it

**Comment by RyanP1991** [comment]
Removed in 1.0.1
