### ISSUE TITLE
Add costume Builds to explore

### ISSUE THREAD

**Issue by blackamberm** [RyanP1991/TWPI-Custom-Pack---1.12#44]
Would be awesome to add costume builds to spawn in the world! It would make the pack super unique!

**Comment by RyanP1991** [comment]
I shall look in to it but no promises

**Comment by Starr12** [comment]
This can be done with Topography, which we'll probably need for the skyblock combo situation. How difficult is the question after that, most likely. if it's easy we'll try adding some and see if we get something good going.
