### ISSUE TITLE
Include MmmMmmMmmMmm

### ISSUE THREAD

**Issue by Starr12** [RyanP1991/TWPI-Custom-Pack---1.12#51]
test dummy mod

**Comment by RyanP1991** [comment]
I question why do we even need it?

**Comment by Hekera** [comment]
From my experience, it has always been difficult to gauge the effectiveness of different weapons (especially between mods). Weapons have damage numbers, but things start getting more difficult as weapon speeds and cross-mod interactions come into account. When combining Psi projectile velocity increases, Astral Sorcery self perks, and Quark increased enchant levels, there isn't a good way to find out the damage of a bow besides seeing the numbers above a dummy. Just my 2 cents.

**Comment by RyanP1991** [comment]
Thank you for the explanation Hek

**Comment by RyanP1991** [comment]
Added in 1.0.4

**Comment by canalpa** [comment]
Yess I was just about to create an issue requesting the same thing and I saw this. 
I approve

**Comment by Hekera** [comment]
litty

**Comment by RyanP1991** [comment]
Added in 1.0.4
