### ISSUE TITLE
(Mod Suggestion) Cosmetic armor

### ISSUE THREAD

**Issue by canalpa** [RyanP1991/TWPI-Custom-Pack---1.12#59]
Cause supremium looks ugly

**Comment by RyanP1991** [comment]
Cosmetic armor still has the bug in which the armor can randomly disappear

**Comment by canalpa** [comment]
Reworked version has fixed that problem. And I believe this mod is incredibly useful. 
Have a poll maybe ?

https://www.curseforge.com/minecraft/mc-mods/cosmetic-armor-reworked

**Comment by RyanP1991** [comment]
So ATM3 which we also run has - CosmeticArmorReworked-1.12.2-v4a and we still had items disappearing

**Comment by canalpa** [comment]
Strange, I've never had items disappearing in ATM3. I thought that was an issue with the cosmetic armors non reworked. I guess we won't have cosmetic armors then :D

**Comment by RyanP1991** [comment]
Rejected
