### ISSUE TITLE
Make Avaritia feasible without killing the server

### ISSUE THREAD

**Issue by Hekera** [RyanP1991/TWPI-Custom-Pack---1.12#61]
~30k material blocks for a single singularity and about 18 stacks of each singularity needed for enough infinity ingots for the full gear set (even more if we decide to add creative recipes involving them). Massive chicken/MysAgri farms, EnvTech miner/processing setups, or wither farms (for EMC) would be needed to gather the resources, likely generating a ton of lag. To avoid this, make Avaritia recipes easier, add [Woot](https://www.curseforge.com/minecraft/mc-mods/woot) for less server-intensive wither farming, and/or add [Erebus](https://www.curseforge.com/minecraft/mc-mods/the-erebus) to greatly reduce the total number of singularities required. Erebus is enough on its own to solve this issue. A drawback of using Erebus is that it makes EMC generation even easier/OP; however, for most normal applications wither farming generates more than enough EMC anyway, so the difference is negligible outside of Avaritia use cases. If Woot is added without Erebus, Avaritia recipes should still be made easier because it does not make that big of a difference on its own.

**Comment by canalpa** [comment]
I completely agree woot is required since its very good for the server it should be in the pack and highly encouraged

**Comment by RyanP1991** [comment]
Woot isn't required because we have Deep Mob Learning instead and will be tweaking the modules from that mod for other items.

**Comment by RyanP1991** [comment]
Although Erebus does look like an interesting exploration mod

**Comment by Hekera** [comment]
Deep Mob Learning has a lower speed ceiling than Woot, making it struggle with the Avaritia material requirements. However, it is still a good replacement for Woot in normal use cases, so I think we should keep it instead of Woot. Therefore, I would recommend adding Erebus instead of Woot to balance Avaritia.

**Comment by RyanP1991** [comment]
How would adding Erebus balance Avaritia?

**Comment by Hekera** [comment]
Erebus has an item called the Wand of Animation, which converts non-block-entity blocks into mob form. This block mob drops the original block when killed. This can be used with Industrial Foregoing mob duplicator to make a block farm. The main use, in an Avaritia context, is to duplicate high-EMC blocks to generate EMC much more efficiently than nether star farms. The fast EMC is then used to make enough singularities for 9 infinity ingots. The infinity ingots would make a block, which was then duplicated via the wand. This was how Avaritia was handled in Project Ozone 3.

**Comment by RyanP1991** [comment]
So basically duping....

**Comment by Hekera** [comment]
Yeah

**Comment by Hekera** [comment]
Keep in mind, the wand can only affect whole blocks that aren't block entities, so it's not like you can dupe your entire ME drive or whatever. Also, like PO2/3, we'd have to alter the wand recipe or gate the dimension behind some other progression mechanic.

**Comment by RyanP1991** [comment]
So do you make the wand or do you find it?

**Comment by Hekera** [comment]
You have to kill a boss to get a Soul Stone, then use it to craft the wand. We could make the recipe require 2 infinity ingots, forcing you to get them "the hard way," before you can abuse the wand to get the rest of the ingots.

**Comment by RyanP1991** [comment]
I'll add a custom recipe for it. Warning it will make you have to explore every mod though

**Comment by Hekera** [comment]
Sure, I approve of making it difficult without making it laggy.
