### ISSUE TITLE
Grief Hazard

### ISSUE THREAD

**Issue by canalpa** [RyanP1991/TWPI-Custom-Pack---1.12#67]
While we were testing with preacher we found out the academycraft abilities can break blocks in claimed territory.

Therefore we should disable the config so none of those abilities actually break blocks

academy-craft-data.conf

we need to add the line (destroy_blocks false) to all the abilities.

**Comment by RyanP1991** [comment]
I don't understand how this config actually works so if you guys can figure it out that would be great.

**Comment by Hekera** [comment]
Something like this:

[academy-craft-data.txt](https://github.com/RyanP1991/TWPI-Custom-Pack---1.12/files/3438675/academy-craft-data.txt)

just change the extension to .conf

**Comment by Hekera** [comment]
You may also want to check if the Meltdowner class's mining rays can break claimed blocks, as they are unaffected by the destroy blocks config.

**Comment by canalpa** [comment]
Placing blocks is ok. Many mods in atm3 can do that in claimed territory I haven't seen that abused yet
as for meltdowner, I will test it asap

**Comment by RyanP1991** [comment]
Went in to configs and changed it to false so we can test it again when I push the update

**Comment by canalpa** [comment]
I have made a config file that disables all abilities from breaking blocks (including the mining rays)
and tested it and confirmed it works
here's the config
[academy config.zip](https://github.com/RyanP1991/TWPI-Custom-Pack---1.12/files/3446600/academy.config.zip)

**Comment by RyanP1991** [comment]
Done in 1.0.7

**Comment by canalpa** [comment]
I have tested all the abilities in the server you can safely close the issue :)

**Comment by RyanP1991** [comment]
Thank you
