### ISSUE TITLE
Random Psideas Config Change

### ISSUE THREAD

**Issue by Hekera** [RyanP1991/TWPI-Custom-Pack---1.12#71]
rpsideas.cfg change:
 ```
# Is the Psionic Pulse potion effect brewable?
    B:enablePsipulse=true
```

**Comment by RyanP1991** [comment]
What does this do Hek

**Comment by Hekera** [comment]
It adds a brewing recipe for a potion that increases psi regen

**Comment by RyanP1991** [comment]
Oh interesting well I have enabled it, makes me wonder what the cost is for it

**Comment by Hekera** [comment]
It's just some Psidust, the effect is pretty short and not very powerful in the first place

**Comment by RyanP1991** [comment]
Ah fair enough either way all done :)
