### ISSUE TITLE
Building Gadgets Creative Paste container

### ISSUE THREAD

**Issue by Starr12** [RyanP1991/TWPI-Custom-Pack---1.12#76]
We added gadgets and creative recipes in the same patch, so we forgot one.

> mods.extendedcrafting.TableCrafting.addShaped(<buildinggadgets:constructionpastecontainercreative>, [
[<ore:blockInsaniumEssence>, <ore:blockInsaniumEssence>, <ore:blockInsaniumEssence>, <ore:blockInsaniumEssence>, <ore:blockInsaniumEssence>, <ore:blockInsaniumEssence>, <ore:blockInsaniumEssence>, <ore:blockInsaniumEssence>, <ore:blockInsaniumEssence>],
[<ore:blockInsaniumEssence>, <thaumcraft:stone_eldritch_tile>, <storagedrawers:upgrade_storage:4>, <storagedrawers:upgrade_storage:4>, <environmentaltech:void_ore_miner_cont_6>, <storagedrawers:upgrade_storage:4>, <storagedrawers:upgrade_storage:4>, <thaumcraft:stone_eldritch_tile>, <ore:blockInsaniumEssence>],
[<ore:blockInsaniumEssence>, <harvestcraft:delightedmealitem>, <railcraft:locomotive_electric>.withTag({model: "railcraft:default"}), <solarflux:solar_panel_8>, <solarflux:solar_panel_8>, <solarflux:solar_panel_8>, <railcraft:locomotive_electric>.withTag({model: "railcraft:default"}), <harvestcraft:delightedmealitem>, <ore:blockInsaniumEssence>],
[<ore:blockInsaniumEssence>, <ironchest:iron_shulker_box_white:2>, <solarflux:solar_panel_8>, <ore:blockEnderium>, <draconicevolution:chaos_shard>, <actuallyadditions:block_crystal_empowered:4>, <solarflux:solar_panel_8>, <ironchest:iron_shulker_box_white:2>, <ore:blockInsaniumEssence>],
[<ore:blockInsaniumEssence>, <botania:manatablet>.withTag({mana: 500000}), <solarflux:solar_panel_8>, <ore:gaiaIngot>, <buildinggadgets:constructionpastecontainert3>, <minecraft:dragon_egg>, <solarflux:solar_panel_8>, <botania:manatablet>.withTag({mana: 500000}), <ore:blockInsaniumEssence>],
[<ore:blockInsaniumEssence>, <ironchest:iron_shulker_box_white:2>, <solarflux:solar_panel_8>, <actuallyadditions:block_crystal_empowered:2>, <ore:netherStar>, <ore:blockInfinity>, <solarflux:solar_panel_8>, <ironchest:iron_shulker_box_white:2>, <ore:blockInsaniumEssence>],
[<ore:blockInsaniumEssence>, <harvestcraft:delightedmealitem>, <railcraft:locomotive_electric>.withTag({model: "railcraft:default"}), <solarflux:solar_panel_8>, <solarflux:solar_panel_8>, <solarflux:solar_panel_8>, <railcraft:locomotive_electric>.withTag({model: "railcraft:default"}), <harvestcraft:delightedmealitem>, <ore:blockInsaniumEssence>],
[<ore:blockInsaniumEssence>, <thaumcraft:stone_eldritch_tile>, <storagedrawers:upgrade_storage:4>, <storagedrawers:upgrade_storage:4>, <thaumcraft:primordial_pearl>, <storagedrawers:upgrade_storage:4>, <storagedrawers:upgrade_storage:4>, <thaumcraft:stone_eldritch_tile>, <ore:blockInsaniumEssence>],
[<ore:blockInsaniumEssence>, <ore:blockInsaniumEssence>, <ore:blockInsaniumEssence>, <ore:blockInsaniumEssence>, <ore:blockInsaniumEssence>, <ore:blockInsaniumEssence>, <ore:blockInsaniumEssence>, <ore:blockInsaniumEssence>, <ore:blockInsaniumEssence>]]);  

I probably did that right?

**Comment by RyanP1991** [comment]
Added in 1.0.7
