### ISSUE TITLE
(Tweak Request) Academycraft

### ISSUE THREAD

**Issue by canalpa** [RyanP1991/TWPI-Custom-Pack---1.12#85]
Currently in the pack by default Academycraft abilities do minuscule damage which is very disappointing. you have to grind for literal hours to get your abilities level up to reach other ability trees and your basic electric shot, vector blast, rip flesh. electron blast or whatever does 3-4 hearts of damage and your most over the top ultimate attack that charges for 10 seconds do like 10 hearts 

https://www.youtube.com/watch?v=07So_lJQyqw

I strongly suggest we multiply all damage done by 3 if we leave the mod as it is and by 5 if we're gonna put the ores in space 

The part you need to edit

    # Global damage scale.
    damage_scale: (Number you want DEFAULT=1)

here's the current config file we're using edited only to multiply all damage done by 5

[5X Config.zip](https://github.com/RyanP1991/TWPI-Custom-Pack---1.12/files/3464168/5X.Config.zip)

**Comment by RyanP1991** [comment]
I have set it to 3 for now
